# Generated by Django 5.2.4 on 2025-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0002_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
