# Generated by Django 5.2.4 on 2025-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hola', '0002_autor_categoria_editorial_libro_prestamo_reserva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='disponible',
        ),
        migrations.AddField(
            model_name='libro',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('reservado', 'Reservado')], default='disponible', max_length=10),
        ),
        migrations.AddField(
            model_name='libro',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='hola.etiqueta'),
        ),
    ]
